version: v2.1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
    type: frontend
    environment: production
spec:
  template:
    metadata:
      labels:
        app: my-app
        type: frontend
        environment: production
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
      - name: busybox-container
        image: busybox:latest
      replicas: 3
      selector:
        matchLabels:
          app: my-app
          type: frontend
          environment: production    